pipeline {
    agent any
    stages {
        stage('Teste Windows') {
            steps {
                bat 'echo "✅ Pipeline funcionando!"'
                bat 'dir'
            }
        }
    }
}
